### ISSUE TITLE
Config requiredPermission Suggestion

### ISSUE THREAD

**Issue by BboyZeroOne** [Maxlego08/zSchedulers#1]
I would like to make a suggestion for zScheduler config options, which adds an additional player permission check before the plugibn execute the command. Here is an example.

```  
example1: # Every day at 18h00
    type: HOURLY
    minute: 33
    minPlayer: 10 
    **requiredPermission: group.noobie**
    commands:
      - "announce Event Starting!"
```

As previously discussed in discord server, you mentioned that you could add a check with PlaceholderAPI too. Thank you!
